apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: quarkus-cqrs-demo
data:
  LOG_DIR: '/tmp/logs'
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
  KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092'
  KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-configmap
  namespace: quarkus-cqrs-demo
data:
  LOG_DIR: '/tmp/logs'

# vim: et sw=2 ts=2 sts=2 :
