apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: quarkus-cqrs-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: strimzi/kafka:0.11.3-kafka-2.1.0
          name: kafka
          command: [
            "sh", "-c",
            "bin/kafka-server-start.sh config/server.properties \
             --override listeners=${KAFKA_LISTENERS} \
             --override advertised.listeners=${KAFKA_ADVERTISED_LISTENERS} \
             --override zookeeper.connect=${KAFKA_ZOOKEEPER_CONNECT}"
          ]
          envFrom:
            - configMapRef:
                name: kafka-configmap
          ports:
            - containerPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: quarkus-cqrs-demo
spec:
  selector:
    app: kafka
  ports:
    - name: client
      port: 9092
  clusterIP: None

# vim: et sw=2 ts=2 sts=2 :
