apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bankaccount-ingress
  namespace: quarkus-cqrs-demo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
    app: bankaccount-ingress
spec:
  rules:
    - http:
        paths:
          - path: /transaction-service/*
            pathType: Prefix
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
          - path: /balance-service/*
            pathType: Prefix
            backend:
              service:
                name: balance-service
                port:
                  number: 8080

# vim: et sw=2 ts=2 sts=2 :
